### ISSUE TITLE
Practica 2 Factibilidad de costo

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-3-practica-de-costos-teamreciclenexus#1]
[Practica 2.docx.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-teamreciclenexus/files/14315221/Practica.2.docx.pdf)

**Comment by Elisahadad** [comment]
17 / 20

**Comment by josealfredo79** [comment]
Bien hecho...
